// ─────────────────────────────────────────────────────────────
//  Kaan — Definición de nichos e industrias
//  Usado en: Settings, Onboarding, API de IA (generate-post, trends)
// ─────────────────────────────────────────────────────────────

export const NICHES = [
  { id: 'real_estate',   label: 'Inmobiliario',           emoji: '🏠', desc: 'Agencias, desarrolladores, agentes'      },
  { id: 'restaurant',    label: 'Restaurantes & F&B',     emoji: '🍽️', desc: 'Restaurantes, bares, cafeterías'         },
  { id: 'tourism',       label: 'Turismo & Hospitalidad', emoji: '🏨', desc: 'Hoteles, tours, experiencias'            },
  { id: 'wellness',      label: 'Wellness & Belleza',     emoji: '💆', desc: 'Spas, salones, yoga, meditación'         },
  { id: 'fitness',       label: 'Fitness',                emoji: '🏋️', desc: 'Gyms, entrenadores, crossfit'           },
  { id: 'health',        label: 'Salud & Clínicas',       emoji: '🏥', desc: 'Médicos, dentistas, estéticas'          },
  { id: 'retail',        label: 'Retail & E-commerce',    emoji: '🛍️', desc: 'Tiendas, boutiques, marcas'            },
  { id: 'education',     label: 'Educación & Coaching',   emoji: '🎓', desc: 'Cursos, coaches, academias'             },
  { id: 'services',      label: 'Servicios Profesionales',emoji: '⚖️', desc: 'Despachos, contadores, consultores'     },
  { id: 'construction',  label: 'Construcción & Arq.',    emoji: '🏗️', desc: 'Constructoras, arquitectos, diseño'    },
]

export const DEFAULT_NICHE = 'real_estate'

// ─────────────────────────────────────────────────────────────
//  Contextos de IA por nicho
//  expertiseDesc → quién es el copywriter
//  expertise     → en qué es experto
//  audience      → a quién le habla
//  trendsContext → contexto para generar tendencias
//  trendTopics   → temas relevantes del nicho
//  fallbackTrends→ tendencias de respaldo si la API falla
// ─────────────────────────────────────────────────────────────
export const NICHE_AI_CONTEXT = {

  real_estate: {
    expertiseDesc: 'marketing inmobiliario en México',
    expertise:     'hooks que detienen el scroll, storytelling inmobiliario, llamadas a la acción que generan leads, plusvalía y tendencias del mercado',
    audience:      'compradores, inversionistas y personas buscando rentar o comprar propiedad',
    trendsContext: 'mercado inmobiliario en México (Riviera Maya, CDMX, Monterrey)',
    trendTopics:   'plusvalía, crédito hipotecario, zonas de crecimiento, inversión en preventa, lifestyle de playa, proceso de compra',
    fallbackTrends: [
      { id:1, emoji:'🏡', titulo:'Consejos para comprar tu primera propiedad',  descripcion:'Lo que nadie te dice antes de firmar.',             tipo:'educativo' },
      { id:2, emoji:'📈', titulo:'Plusvalía en la Riviera Maya',                descripcion:'Las zonas con mayor crecimiento inmobiliario.',      tipo:'inversion' },
      { id:3, emoji:'🌊', titulo:'Vivir cerca del mar — el lifestyle real',     descripcion:'Cómo es el día a día en zona costera.',              tipo:'lifestyle' },
      { id:4, emoji:'💰', titulo:'Crédito hipotecario en 2025',                 descripcion:'Cómo acceder y qué opciones existen.',               tipo:'proceso'   },
      { id:5, emoji:'🏢', titulo:'Invertir en departamentos en preventa',       descripcion:'Por qué la preventa sigue siendo una apuesta ganadora.', tipo:'inversion' },
      { id:6, emoji:'🔑', titulo:'Proceso de compra paso a paso',               descripcion:'Guía completa para comprar en México.',              tipo:'proceso'   },
      { id:7, emoji:'🏖️', titulo:'Propiedades vacacionales rentables',         descripcion:'Genera ingresos con una propiedad en zona turística.',tipo:'mercado'   },
      { id:8, emoji:'🌳', titulo:'Amenidades más valoradas en 2025',            descripcion:'Qué buscan hoy los compradores modernos.',           tipo:'mercado'   },
    ],
  },

  restaurant: {
    expertiseDesc: 'marketing para restaurantes y F&B en México',
    expertise:     'contenido que genera reservaciones y visitas, fotografía de alimentos, promociones, experiencias gastronómicas, storytelling de cocina',
    audience:      'comensales locales y turistas que buscan experiencias gastronómicas únicas',
    trendsContext: 'industria restaurantera y F&B en México',
    trendTopics:   'menús de temporada, experiencias temáticas, happy hours, brunch, eventos especiales, chef specials, delivery, reseñas',
    fallbackTrends: [
      { id:1, emoji:'🍳', titulo:'El plato estrella de la temporada',           descripcion:'Cómo presentar tu menú de temporada.',              tipo:'mercado'   },
      { id:2, emoji:'🥂', titulo:'Experiencias más allá de la comida',          descripcion:'Eventos, maridajes y noches temáticas.',             tipo:'lifestyle' },
      { id:3, emoji:'📸', titulo:'Fotografía que vende antes del primer bocado',descripcion:'Tips visuales para que tu comida irresistible.',      tipo:'educativo' },
      { id:4, emoji:'⭐', titulo:'Reseñas: tu mejor estrategia de marketing',   descripcion:'Cómo convertir clientes en embajadores.',            tipo:'proceso'   },
      { id:5, emoji:'🚀', titulo:'Delivery: más que una opción, un canal',      descripcion:'Cómo maximizar tus pedidos en línea.',               tipo:'mercado'   },
      { id:6, emoji:'🍹', titulo:'Happy hour que llena mesas',                  descripcion:'Diseña una promo irresistible para entre semana.',   tipo:'inversion' },
      { id:7, emoji:'👨‍🍳', titulo:'El chef tiene la palabra',                 descripcion:'Humaniza tu marca con historias del equipo.',         tipo:'lifestyle' },
      { id:8, emoji:'🌮', titulo:'Ingrediente local: diferenciador real',       descripcion:'El origen de tus productos como historia de marca.',  tipo:'educativo' },
    ],
  },

  tourism: {
    expertiseDesc: 'marketing de turismo y hospitalidad en México',
    expertise:     'contenido de viajes y experiencias, storytelling de destinos, actividades, y contenido que genera reservaciones',
    audience:      'viajeros nacionales e internacionales que buscan experiencias en México',
    trendsContext: 'turismo y hospitalidad en México (Riviera Maya, CDMX, Oaxaca, etc.)',
    trendTopics:   'temporadas turísticas, experiencias únicas, turismo de aventura, lujo accesible, turismo sustentable, off-the-beaten-path',
    fallbackTrends: [
      { id:1, emoji:'🤿', titulo:'Experiencias que no encuentras en TripAdvisor',descripcion:'Activa tu diferenciador con tours exclusivos.',        tipo:'lifestyle' },
      { id:2, emoji:'🌅', titulo:'Temporada alta: cómo preparar tu oferta',     descripcion:'Estrategia de contenido para llenar tu agenda.',     tipo:'mercado'   },
      { id:3, emoji:'♻️', titulo:'Turismo responsable como ventaja competitiva',descripcion:'El viajero moderno valora la sostenibilidad.',        tipo:'educativo' },
      { id:4, emoji:'📱', titulo:'UGC: que tus huéspedes sean tu marketing',    descripcion:'Cómo motivar reseñas y contenido generado por usuarios.', tipo:'proceso' },
      { id:5, emoji:'🏊', titulo:'Amenidades que enamoran en fotos',            descripcion:'Las instalaciones más compartidas en Instagram.',     tipo:'lifestyle' },
      { id:6, emoji:'🌮', titulo:'Gastronomía local como atractivo',            descripcion:'La comida como parte de la experiencia.',             tipo:'mercado'   },
      { id:7, emoji:'💑', titulo:'Turismo de bodas y lunas de miel',            descripcion:'Un mercado con alto ticket y fidelidad.',             tipo:'inversion' },
      { id:8, emoji:'🗺️', titulo:'Guía de la zona: sé el experto local',       descripcion:'Contenido de valor que posiciona tu marca.',          tipo:'educativo' },
    ],
  },

  wellness: {
    expertiseDesc: 'marketing para wellness, spas y belleza en México',
    expertise:     'contenido de bienestar y transformación, before/after, rituales, y contenido que genera reservaciones y citas',
    audience:      'personas que buscan bienestar, relajación, belleza y autocuidado',
    trendsContext: 'industria wellness y belleza en México',
    trendTopics:   'rituales de temporada, autocuidado, transformaciones, Día de la Madre, preparación para eventos, bienestar mental, tendencias de tratamientos',
    fallbackTrends: [
      { id:1, emoji:'🧖', titulo:'Ritual del mes: el tratamiento estrella',      descripcion:'Presenta tu servicio más popular con contexto.',     tipo:'mercado'   },
      { id:2, emoji:'✨', titulo:'Before & after que inspiran',                  descripcion:'Cómo mostrar resultados respetando la privacidad.',   tipo:'proceso'   },
      { id:3, emoji:'💆', titulo:'Autocuidado como inversión, no como lujo',     descripcion:'Cambia la percepción de precio con valor.',           tipo:'educativo' },
      { id:4, emoji:'🌸', titulo:'Temporada de bodas: el momento de los spas',  descripcion:'Cómo posicionarte para novias y festejadas.',        tipo:'inversion' },
      { id:5, emoji:'🧘', titulo:'Bienestar mental + físico: la tendencia 2025',descripcion:'Integra el componente emocional en tus servicios.',   tipo:'lifestyle' },
      { id:6, emoji:'🎁', titulo:'Regalos de experiencia vs. regalos materiales',descripcion:'Posiciona tus gift cards para fechas especiales.',    tipo:'mercado'   },
      { id:7, emoji:'👩‍💼', titulo:'La terapeuta que hay detrás del servicio',  descripcion:'Humaniza tu marca con historias del equipo.',         tipo:'lifestyle' },
      { id:8, emoji:'🌿', titulo:'Ingredientes naturales como diferenciador',    descripcion:'El origen de tus productos como propuesta de valor.', tipo:'educativo' },
    ],
  },

  fitness: {
    expertiseDesc: 'marketing para fitness y deporte en México',
    expertise:     'contenido motivacional, transformaciones, rutinas, retos, y contenido que genera membresías y asistencia a clases',
    audience:      'personas activas o que quieren comenzar a ejercitarse y mejorar su condición física',
    trendsContext: 'industria fitness en México',
    trendTopics:   'reto mensual, temporada de verano, regreso a clases, año nuevo, transformaciones, CrossFit, funcional, suplementación',
    fallbackTrends: [
      { id:1, emoji:'💪', titulo:'Reto del mes: el contenido que más convierte',  descripcion:'Cómo lanzar un reto que genere inscripciones.',      tipo:'proceso'   },
      { id:2, emoji:'🏆', titulo:'Transformaciones reales de tus miembros',       descripcion:'El contenido más poderoso para el sector fitness.',  tipo:'mercado'   },
      { id:3, emoji:'☀️', titulo:'Operación verano: estrategia de contenido',    descripcion:'Cómo capitalizar la temporada más activa del año.',   tipo:'inversion' },
      { id:4, emoji:'🥗', titulo:'Nutrición como parte del servicio',             descripcion:'Amplía tu valor con contenido de alimentación.',      tipo:'educativo' },
      { id:5, emoji:'🧠', titulo:'Fitness mental: mindset de entrenamiento',      descripcion:'La tendencia que conecta ejercicio con bienestar.',   tipo:'lifestyle' },
      { id:6, emoji:'📊', titulo:'Resultados con datos: el gym que mide',         descripcion:'Cómo mostrar progreso con métricas reales.',          tipo:'educativo' },
      { id:7, emoji:'👥', titulo:'Comunidad: tu mayor ventaja competitiva',       descripcion:'Por qué la gente se queda por las personas.',         tipo:'lifestyle' },
      { id:8, emoji:'🆕', titulo:'Nuevas clases y tendencias en entrenamiento',   descripcion:'Mantente relevante mostrando innovación.',            tipo:'mercado'   },
    ],
  },

  health: {
    expertiseDesc: 'marketing para salud y clínicas en México',
    expertise:     'contenido educativo de salud, prevención, testimoniales, y contenido que genera consultas y citas',
    audience:      'pacientes y personas preocupadas por su salud y bienestar',
    trendsContext: 'salud y bienestar médico en México',
    trendTopics:   'prevención estacional, meses de concientización, salud dental, estética, checkups, tratamientos modernos, bienestar preventivo',
    fallbackTrends: [
      { id:1, emoji:'🦷', titulo:'Salud dental: el servicio más postergado',     descripcion:'Cómo generar urgencia en tus pacientes potenciales.', tipo:'mercado'   },
      { id:2, emoji:'🩺', titulo:'Checkup preventivo: el mejor seguro de vida',  descripcion:'Contenido educativo que posiciona la prevención.',    tipo:'educativo' },
      { id:3, emoji:'💉', titulo:'Vacunación de temporada: actúa con anticipación',descripcion:'Comunica el calendario de vacunas oportunamente.',  tipo:'proceso'   },
      { id:4, emoji:'😊', titulo:'Testimonial de paciente: el contenido más confiable',descripcion:'Cómo pedir y presentar casos de éxito.',        tipo:'proceso'   },
      { id:5, emoji:'🌡️', titulo:'Temporada de gripes y alergias: sé el recurso',descripcion:'Contenido de valor en el momento oportuno.',         tipo:'mercado'   },
      { id:6, emoji:'🧬', titulo:'Medicina estética: tendencias 2025',           descripcion:'Los tratamientos más solicitados y cómo comunicarlos.',tipo:'inversion' },
      { id:7, emoji:'👨‍⚕️', titulo:'Humaniza a tu médico o especialista',        descripcion:'La confianza se construye con el lado humano.',       tipo:'lifestyle' },
      { id:8, emoji:'📋', titulo:'Derechos del paciente: contenido que conecta', descripcion:'Educa y diferénciate con transparencia.',             tipo:'educativo' },
    ],
  },

  retail: {
    expertiseDesc: 'marketing para retail y e-commerce en México',
    expertise:     'lanzamiento de productos, ventas, descuentos, unboxing, tendencias, y contenido que genera ventas directas',
    audience:      'compradores en línea y en tienda que buscan productos y tendencias',
    trendsContext: 'retail y e-commerce en México',
    trendTopics:   'temporadas de venta (Buen Fin, Hot Sale, Navidad), nuevas colecciones, drops, tendencias de moda, UGC, reseñas de producto',
    fallbackTrends: [
      { id:1, emoji:'🛍️', titulo:'Lanzamiento de colección: el evento del mes',  descripcion:'Genera expectativa antes del drop.',                  tipo:'mercado'   },
      { id:2, emoji:'📦', titulo:'Unboxing: el contenido que vende sin vender',   descripcion:'Cómo el packaging cuenta la historia de tu marca.',   tipo:'lifestyle' },
      { id:3, emoji:'⭐', titulo:'Reseña de cliente real: prueba social',         descripcion:'UGC como motor de conversión.',                       tipo:'proceso'   },
      { id:4, emoji:'🔖', titulo:'Promo flash: urgencia que convierte',           descripcion:'Diseña ofertas de tiempo limitado efectivas.',         tipo:'inversion' },
      { id:5, emoji:'🎨', titulo:'Storytelling de producto: más que un artículo', descripcion:'La historia detrás de lo que vendes.',                tipo:'educativo' },
      { id:6, emoji:'🤳', titulo:'Try-on y comparativas de producto',             descripcion:'Contenido que elimina la fricción de comprar en línea.',tipo:'proceso'  },
      { id:7, emoji:'🌱', titulo:'Marca sustentable: diferenciador actual',       descripcion:'Comunica tu impacto y conecta con el consumidor consciente.', tipo:'educativo' },
      { id:8, emoji:'🎁', titulo:'Guías de regalo por temporada',                 descripcion:'Facilita la decisión de compra en fechas clave.',      tipo:'mercado'   },
    ],
  },

  education: {
    expertiseDesc: 'marketing para educación y coaching en México',
    expertise:     'contenido educativo de valor, testimoniales, resultados de alumnos, y contenido que genera inscripciones y consultas',
    audience:      'personas que quieren aprender, crecer profesionalmente o emprender',
    trendsContext: 'educación online y presencial, y coaching en México',
    trendTopics:   'inicio de cursos, certificaciones, resultados de alumnos, emprendimiento, tendencias del mercado laboral, habilidades del futuro',
    fallbackTrends: [
      { id:1, emoji:'🎓', titulo:'Historia de transformación de un alumno',      descripcion:'El testimonio más poderoso que puedes publicar.',     tipo:'proceso'   },
      { id:2, emoji:'📊', titulo:'Habilidades más demandadas en 2025',           descripcion:'Posiciona tu oferta con contexto del mercado laboral.',tipo:'mercado'   },
      { id:3, emoji:'🚀', titulo:'De cero a emprender: el proceso real',         descripcion:'Contenido honesto que conecta con tu audiencia.',     tipo:'lifestyle' },
      { id:4, emoji:'💡', titulo:'Contenido gratuito de valor como anzuelo',     descripcion:'Cómo dar para recibir: lead magnets que convierten.', tipo:'inversion' },
      { id:5, emoji:'🤝', titulo:'Comunidad de alumnos como diferenciador',      descripcion:'El networking vale tanto como el conocimiento.',      tipo:'educativo' },
      { id:6, emoji:'📅', titulo:'Apertura de nueva cohorte: genera urgencia',   descripcion:'Estrategia de lanzamiento de programa.',              tipo:'mercado'   },
      { id:7, emoji:'🧠', titulo:'El coach detrás del método: credibilidad',     descripcion:'Tu historia y experiencia como propuesta de valor.',  tipo:'lifestyle' },
      { id:8, emoji:'📱', titulo:'Micro-aprendizaje en redes: tendencia 2025',   descripcion:'Cómo educar en 60 segundos y ganar autoridad.',       tipo:'educativo' },
    ],
  },

  services: {
    expertiseDesc: 'marketing para servicios profesionales en México',
    expertise:     'contenido educativo, casos de éxito, credibilidad, y contenido que genera consultas y clientes',
    audience:      'empresas y personas que necesitan servicios legales, contables o de consultoría especializada',
    trendsContext: 'servicios profesionales, legal, contable y consultoría en México',
    trendTopics:   'cambios fiscales, declaraciones anuales, reformas legales, emprendimiento, protección patrimonial, facturación electrónica',
    fallbackTrends: [
      { id:1, emoji:'📋', titulo:'Cambios fiscales que afectan a tu empresa',    descripcion:'Posiciona tu expertise con contenido de actualidad.',  tipo:'educativo' },
      { id:2, emoji:'⚖️', titulo:'Error común que le cuesta caro a los negocios',descripcion:'El contenido de "qué evitar" genera alta retención.',  tipo:'proceso'   },
      { id:3, emoji:'🏢', titulo:'Protección patrimonial: no es solo para ricos',descripcion:'Democratiza el acceso al conocimiento financiero-legal.',tipo:'educativo' },
      { id:4, emoji:'💡', titulo:'Caso de éxito: cómo resolvimos el problema X', descripcion:'Sin revelar datos, muestra tu proceso y resultado.',   tipo:'proceso'   },
      { id:5, emoji:'📅', titulo:'Calendario fiscal: las fechas que no puedes perder',descripcion:'Contenido de utilidad recurrente para tu audiencia.',tipo:'mercado' },
      { id:6, emoji:'🤝', titulo:'Por qué contratar un profesional vs. hacerlo solo',descripcion:'Educa sobre el costo real de no asesorarse.',       tipo:'inversion' },
      { id:7, emoji:'🌐', titulo:'Tu despacho en LinkedIn vs. Instagram',        descripcion:'Cómo adaptar tu mensaje a cada plataforma.',           tipo:'proceso'   },
      { id:8, emoji:'👥', titulo:'Testimonial de cliente: el activo más valioso',descripcion:'Cómo pedir y presentar referencias profesionales.',   tipo:'lifestyle' },
    ],
  },

  construction: {
    expertiseDesc: 'marketing para construcción y arquitectura en México',
    expertise:     'portfolio de proyectos, procesos constructivos, diseño, materiales, y contenido que genera leads de clientes',
    audience:      'personas y empresas que buscan construir, remodelar o diseñar espacios',
    trendsContext: 'construcción, arquitectura y diseño de interiores en México',
    trendTopics:   'tendencias de diseño, materiales sustentables, home renovation, espacios pequeños, arquitectura bioclimática, proceso de construcción',
    fallbackTrends: [
      { id:1, emoji:'🏗️', titulo:'El proceso de una obra en 8 etapas',           descripcion:'Educa y genera confianza mostrando tu metodología.',   tipo:'proceso'   },
      { id:2, emoji:'✨', titulo:'Antes y después: la transformación visual',     descripcion:'El contenido más efectivo del sector construcción.',   tipo:'mercado'   },
      { id:3, emoji:'🌿', titulo:'Construcción sustentable: el futuro es hoy',   descripcion:'Materiales y técnicas eco-friendly como diferenciador.',tipo:'educativo' },
      { id:4, emoji:'📐', titulo:'Tendencias de diseño de interiores 2025',      descripcion:'Qué buscan hoy los clientes en sus espacios.',         tipo:'mercado'   },
      { id:5, emoji:'💡', titulo:'El error más caro al remodelar',               descripcion:'Contenido preventivo que posiciona tu expertise.',     tipo:'educativo' },
      { id:6, emoji:'🏠', titulo:'Cuánto cuesta construir en m² hoy en México',  descripcion:'Transparencia de precios como estrategia de confianza.',tipo:'inversion' },
      { id:7, emoji:'👷', titulo:'El equipo detrás de cada obra',                descripcion:'Humaniza tu marca con el talento que hay detrás.',     tipo:'lifestyle' },
      { id:8, emoji:'🛋️', titulo:'Diseño de espacios pequeños: mucho con poco', descripcion:'Alta demanda y búsquedas en auge en México.',          tipo:'proceso'   },
    ],
  },
}

// ─────────────────────────────────────────────────────────────
//  Herramientas de negocio por nicho
//  calc   → calculadora de pipeline/proyección de ingresos
//  diagDesc → descripción del diagnóstico de marketing
//  seasonLabel / seasonSubtitle / seasonDesc → encabezados estacionalidad
//  seasonality → 12 meses con level(1-3), tip, budget
// ─────────────────────────────────────────────────────────────
export const NICHE_TOOLS = {

  real_estate: {
    label: 'Herramientas Inmobiliarias',
    calc: {
      title: 'Pipeline de Comisiones',
      icon: '💎',
      desc: 'Meta Ads te dice cuántos leads tienes. Kaan te dice cuánto valen en comisiones potenciales.',
      f1Label: 'Leads este mes', f1P: 'ej. 45',
      f2Label: 'Precio prop. (MXN)', f2P: 'ej. 2,500,000',
      f3Label: 'Comisión (%)', f3P: '3', f3D: '3',
      f4Label: 'Tasa cierre (%)', f4P: '10', f4D: '10',
      hasGoal: true, goalLabel: 'Meta mensual de comisiones (MXN, opcional)', goalP: 'ej. 150,000',
      resultTitle: 'Tu pipeline vale',
      resultUnit: 'en comisiones potenciales',
      compute: (l,p,c,r) => l*(r/100)*p*(c/100),
      sub: (l,p,c,r) => `${(l*(r/100)).toFixed(1)} cierres esperados`,
    },
    diagDesc: 'Revisa qué tan completa está tu infraestructura de marketing inmobiliario.',
    seasonLabel: 'Estacionalidad Inmobiliaria',
    seasonSubtitle: 'Cuándo invertir más (o menos) en México',
    seasonDesc: 'Ninguna plataforma te avisa sobre la estacionalidad del mercado inmobiliario. Kaan sí.',
    seasonality: [
      { m:'Ene', level:1, tip:'Post-navidad: CPL caro, bajo interés comprador. Ideal para construir audiencias baratas.', budget:'Reduce' },
      { m:'Feb', level:2, tip:'Recuperación lenta. Vacaciones escolares impulsan búsqueda de propiedades vacacionales.', budget:'Normal' },
      { m:'Mar', level:3, tip:'Pico primaveral. Familias planifican mudanza antes del fin de cursos. Escala presupuesto.', budget:'Escala' },
      { m:'Abr', level:3, tip:'Semana Santa inspira compras vacacionales. Alta demanda en zonas turísticas.', budget:'Escala' },
      { m:'May', level:3, tip:'Último mes antes del verano. Alta demanda residencial. Aumenta inversión.', budget:'Escala' },
      { m:'Jun', level:2, tip:'Inicio de vacaciones. Demanda mixta. Mantén presupuesto pero varía creativos.', budget:'Normal' },
      { m:'Jul', level:1, tip:'Pleno verano. Compradores de vacaciones, no residencial. Segmenta bien.', budget:'Reduce' },
      { m:'Ago', level:2, tip:'Regreso a clases activa búsqueda de zonas residenciales con colegios cercanos.', budget:'Normal' },
      { m:'Sep', level:2, tip:'Fiestas patrias. Sentimiento positivo. Recuperación de demanda residencial.', budget:'Normal' },
      { m:'Oct', level:3, tip:'Segundo pico del año. Excelente momento para escalar campañas de leads.', budget:'Escala' },
      { m:'Nov', level:1, tip:'Buen Fin distrae compradores. CPL sube 30-50%. Reduce budget y espera diciembre.', budget:'Pausa' },
      { m:'Dic', level:1, tip:'Congelamiento total. Nadie compra casa en navidad. Usa para planificar enero.', budget:'Pausa' },
    ],
  },

  restaurant: {
    label: 'Herramientas para Restaurantes',
    calc: {
      title: 'Proyección de Ingresos',
      icon: '🍽️',
      desc: 'Convierte tus leads de Meta en ingresos reales estimando ticket, retención y frecuencia de visita.',
      f1Label: 'Clientes nuevos (leads)', f1P: 'ej. 80',
      f2Label: 'Ticket promedio (MXN)', f2P: 'ej. 350',
      f3Label: '% clientes que regresan', f3P: '40', f3D: '40',
      f4Label: 'Visitas/mes promedio', f4P: '2', f4D: '2',
      hasGoal: true, goalLabel: 'Meta mensual de ingresos (MXN, opcional)', goalP: 'ej. 120,000',
      resultTitle: 'Ingresos proyectados',
      resultUnit: 'de tus clientes de ads',
      compute: (l,p,c,r) => l*p + l*(c/100)*p*(r-1),
      sub: (l,p,c,r) => `${l} nuevos + ${Math.round(l*(c/100))} que regresan ${r}x/mes`,
    },
    diagDesc: 'Revisa qué tan completa está tu infraestructura de marketing para restaurantes y F&B.',
    seasonLabel: 'Estacionalidad Restaurantera',
    seasonSubtitle: 'Cuándo invertir más en ads de comida',
    seasonDesc: 'El comportamiento del comensal cambia cada mes. Kaan te dice cuándo empujar y cuándo conservar.',
    seasonality: [
      { m:'Ene', level:1, tip:'Post-fiestas: gasto reducido, dietas de año nuevo. Ideal para menús "saludables" y promos de reactivación.', budget:'Reduce' },
      { m:'Feb', level:3, tip:'San Valentín genera el pico más alto del año en restaurantes. Escala desde el 1 de febrero.', budget:'Escala' },
      { m:'Mar', level:2, tip:'Demanda estable. Ideal para campañas de fidelización y programas de lealtad.', budget:'Normal' },
      { m:'Abr', level:3, tip:'Semana Santa y vacaciones escolares: familias salen a comer más. Refuerza brunch y experiencias.', budget:'Escala' },
      { m:'May', level:3, tip:'Día de las Madres (segundo domingo) es el día de mayor venta del año. Reserva presupuesto aquí.', budget:'Escala' },
      { m:'Jun', level:2, tip:'Post-mamás. Demanda regular. Buena época para lanzar menús de verano.', budget:'Normal' },
      { m:'Jul', level:2, tip:'Vacaciones familiares. Alto tráfico en zonas turísticas; bajo en zonas de oficinas.', budget:'Normal' },
      { m:'Ago', level:1, tip:'Regreso a clases reduce salidas familiares. Enfócate en lunch ejecutivo y delivery.', budget:'Reduce' },
      { m:'Sep', level:2, tip:'Fiestas patrias dispara consumo de antojitos y cenas grupales. Temática mexicana funciona.', budget:'Normal' },
      { m:'Oct', level:2, tip:'Temporada de eventos corporativos. Activa paquetes de grupos y eventos.', budget:'Normal' },
      { m:'Nov', level:3, tip:'Posadas corporativas arrancan. Buen Fin impulsa delivery y take-out. Escala ads.', budget:'Escala' },
      { m:'Dic', level:3, tip:'Mes más alto del año. Posadas, cenas de navidad y año nuevo. No reduzcas un peso.', budget:'Escala' },
    ],
  },

  tourism: {
    label: 'Herramientas de Turismo',
    calc: {
      title: 'Calculadora de Reservaciones',
      icon: '🏨',
      desc: 'Estima cuántas reservaciones y ingresos puedes esperar del tráfico que generan tus anuncios.',
      f1Label: 'Leads o consultas', f1P: 'ej. 60',
      f2Label: 'Precio por reservación (MXN)', f2P: 'ej. 4,500',
      f3Label: 'Tasa de conversión (%)', f3P: '15', f3D: '15',
      f4Label: 'Noches o días promedio', f4P: '3', f4D: '3',
      hasGoal: true, goalLabel: 'Meta mensual de ingresos (MXN, opcional)', goalP: 'ej. 200,000',
      resultTitle: 'Ingresos estimados',
      resultUnit: 'en reservaciones',
      compute: (l,p,c,r) => l*(c/100)*p*r,
      sub: (l,p,c,r) => `${Math.round(l*(c/100))} reservaciones · ${r} noches promedio`,
    },
    diagDesc: 'Evalúa la salud de tu setup digital para atraer turistas y generar reservaciones en línea.',
    seasonLabel: 'Temporadas Turísticas',
    seasonSubtitle: 'Cuándo escalar tus campañas de turismo',
    seasonDesc: 'Los destinos turísticos tienen picos muy marcados. Anticípate con presupuesto antes que tu competencia.',
    seasonality: [
      { m:'Ene', level:3, tip:'Temporada alta de sol y playa post-navidad. Turistas internacionales en zonas costeras.', budget:'Escala' },
      { m:'Feb', level:2, tip:'Transición. Escala para destinos de romance (San Valentín) y naturaleza.', budget:'Normal' },
      { m:'Mar', level:3, tip:'Spring Break americano llena costas. Ideal para comunicar en inglés y escalar.', budget:'Escala' },
      { m:'Abr', level:3, tip:'Semana Santa: el mayor movimiento turístico interno del año. Presupuesto máximo.', budget:'Escala' },
      { m:'May', level:2, tip:'Post-Semana Santa. Caída natural. Mantén visibilidad para capturar verano temprano.', budget:'Normal' },
      { m:'Jun', level:2, tip:'Inicio de vacaciones de verano. Familias planifican viajes. Activa campañas de reserva anticipada.', budget:'Normal' },
      { m:'Jul', level:3, tip:'Temporada alta de verano. Playa, aventura, ecoturismo al tope. No recortes.', budget:'Escala' },
      { m:'Ago', level:3, tip:'Último mes de vacaciones de verano. Alta demanda familiar. Mantén escala.', budget:'Escala' },
      { m:'Sep', level:1, tip:'Temporada baja. Reduce budget y usa el período para preparar creativos de temporada alta.', budget:'Reduce' },
      { m:'Oct', level:1, tip:'Temporada baja general, excepto Día de Muertos (fin de mes) que mueve turismo cultural.', budget:'Reduce' },
      { m:'Nov', level:2, tip:'Turismo de otoño y preparación navideña. Activa campañas de anticipación.', budget:'Normal' },
      { m:'Dic', level:3, tip:'Navidad y año nuevo: pico máximo de turismo nacional e internacional.', budget:'Escala' },
    ],
  },

  wellness: {
    label: 'Herramientas de Wellness',
    calc: {
      title: 'Proyección de Membresías',
      icon: '💆',
      desc: 'Calcula el valor real de tus leads considerando conversión, precio y tiempo de permanencia del cliente.',
      f1Label: 'Leads este mes', f1P: 'ej. 50',
      f2Label: 'Precio membresía/mes (MXN)', f2P: 'ej. 800',
      f3Label: 'Tasa de conversión (%)', f3P: '20', f3D: '20',
      f4Label: 'Meses de permanencia prom.', f4P: '5', f4D: '5',
      hasGoal: true, goalLabel: 'Meta mensual de ingresos (MXN, opcional)', goalP: 'ej. 40,000',
      resultTitle: 'LTV generado',
      resultUnit: 'en membresías proyectadas',
      compute: (l,p,c,r) => l*(c/100)*p*r,
      sub: (l,p,c,r) => `${Math.round(l*(c/100))} nuevos miembros · ${r} meses promedio`,
    },
    diagDesc: 'Evalúa tu presencia digital para atraer clientes de wellness, spa y bienestar.',
    seasonLabel: 'Estacionalidad Wellness',
    seasonSubtitle: 'Cuándo tu cliente busca bienestar',
    seasonDesc: 'Los hábitos de autocuidado tienen ciclos claros. Saber cuándo activar tus ads marca la diferencia.',
    seasonality: [
      { m:'Ene', level:3, tip:'Año nuevo, propósitos de bienestar. La mayor demanda del año para spas y wellness. Escala.', budget:'Escala' },
      { m:'Feb', level:3, tip:'San Valentín: parejas buscan experiencias de spa y relajación. Muy alto ROI.', budget:'Escala' },
      { m:'Mar', level:2, tip:'Demanda estable. Buen momento para activar membresías y paquetes de 3 meses.', budget:'Normal' },
      { m:'Abr', level:2, tip:'Semana Santa activa turismo de bienestar en destinos vacacionales.', budget:'Normal' },
      { m:'May', level:3, tip:'Día de las Madres: el regalo de spa más popular. Activa paquetes de regalo.', budget:'Escala' },
      { m:'Jun', level:2, tip:'Inicio de verano. Demanda de tratamientos estéticos para "temporada de playa".', budget:'Normal' },
      { m:'Jul', level:1, tip:'Vacaciones: clientes salen de rutina. Reduce y prepara campañas de regreso.', budget:'Reduce' },
      { m:'Ago', level:2, tip:'Regreso a rutinas. Reactiva membresías con promos de "reinicio saludable".', budget:'Normal' },
      { m:'Sep', level:2, tip:'Temporada de estrés laboral activa demanda de masajes y relajación.', budget:'Normal' },
      { m:'Oct', level:2, tip:'Demanda estable. Buen momento para promociones de otoño y preparación de fin de año.', budget:'Normal' },
      { m:'Nov', level:3, tip:'Buen Fin y pre-navidad: regalos de spa muy buscados. Activa gift cards.', budget:'Escala' },
      { m:'Dic', level:2, tip:'Regalos navideños de experiencias de bienestar. Mantén presencia pero no escales.', budget:'Normal' },
    ],
  },

  fitness: {
    label: 'Herramientas de Fitness',
    calc: {
      title: 'Proyección de Socios',
      icon: '🏋️',
      desc: 'Proyecta los ingresos de nuevos socios considerando conversión, mensualidad y tiempo de permanencia.',
      f1Label: 'Leads este mes', f1P: 'ej. 100',
      f2Label: 'Precio membresía/mes (MXN)', f2P: 'ej. 600',
      f3Label: 'Tasa de conversión (%)', f3P: '25', f3D: '25',
      f4Label: 'Meses de permanencia prom.', f4P: '4', f4D: '4',
      hasGoal: true, goalLabel: 'Meta mensual de ingresos (MXN, opcional)', goalP: 'ej. 60,000',
      resultTitle: 'LTV de nuevos socios',
      resultUnit: 'en ingresos proyectados',
      compute: (l,p,c,r) => l*(c/100)*p*r,
      sub: (l,p,c,r) => `${Math.round(l*(c/100))} nuevos socios · ${r} meses promedio`,
    },
    diagDesc: 'Revisa la salud de tu infraestructura digital para atraer nuevos socios al gym o estudio.',
    seasonLabel: 'Estacionalidad Fitness',
    seasonSubtitle: 'Cuándo la gente quiere ponerse fit',
    seasonDesc: 'Las inscripciones a gimnasios siguen patrones predecibles. Anticípate y gana mercado.',
    seasonality: [
      { m:'Ene', level:3, tip:'El mes de mayor inscripción del año. Propósitos de año nuevo = tu mejor oportunidad. Escala al máximo.', budget:'Escala' },
      { m:'Feb', level:2, tip:'Baja leve post-enero, pero sigue alto. Muchos mantienen el propósito las primeras semanas.', budget:'Normal' },
      { m:'Mar', level:2, tip:'Demanda estable. Activa el mensaje de "temporada de playa" para mantener motivación.', budget:'Normal' },
      { m:'Abr', level:3, tip:'Preparación para verano. Alta demanda de transformación física. Muy buen período.', budget:'Escala' },
      { m:'May', level:3, tip:'El mensaje "listo para el verano" tiene el mayor engagement del año. Escala.', budget:'Escala' },
      { m:'Jun', level:2, tip:'Inicio de vacaciones. Mantén presencia pero baja un poco para zonas escolares.', budget:'Normal' },
      { m:'Jul', level:1, tip:'Vacaciones escolares. Muchos salen de rutina. Enfócate en retención, no adquisición.', budget:'Reduce' },
      { m:'Ago', level:2, tip:'Regreso a rutinas y clases. Segunda ola de inscripciones. Buena temporada.', budget:'Normal' },
      { m:'Sep', level:2, tip:'Estabilidad. Activa campañas de "reto de 30 días" para generar urgencia.', budget:'Normal' },
      { m:'Oct', level:1, tip:'Temporada tranquila. Invierte en retención y comunidad más que adquisición.', budget:'Reduce' },
      { m:'Nov', level:1, tip:'Buen Fin distrae y sube CPL. Prepara campaña de enero desde ahora.', budget:'Reduce' },
      { m:'Dic', level:1, tip:'Diciembre es el peor mes para inscripciones. Guarda presupuesto para enero.', budget:'Pausa' },
    ],
  },

  health: {
    label: 'Herramientas de Salud',
    calc: {
      title: 'Valor de Pacientes',
      icon: '🏥',
      desc: 'Proyecta el valor anual de los pacientes que generan tus campañas de Meta Ads.',
      f1Label: 'Leads / consultas recibidas', f1P: 'ej. 40',
      f2Label: 'Precio por consulta (MXN)', f2P: 'ej. 900',
      f3Label: 'Tasa de conversión (%)', f3P: '30', f3D: '30',
      f4Label: 'Consultas/año por paciente', f4P: '4', f4D: '4',
      hasGoal: true, goalLabel: 'Meta mensual de ingresos (MXN, opcional)', goalP: 'ej. 50,000',
      resultTitle: 'Valor anual de pacientes',
      resultUnit: 'en ingresos proyectados',
      compute: (l,p,c,r) => l*(c/100)*p*r,
      sub: (l,p,c,r) => `${Math.round(l*(c/100))} pacientes nuevos · ${r} consultas/año`,
    },
    diagDesc: 'Evalúa tu presencia digital para atraer pacientes y hacer crecer tu clínica o consultorio.',
    seasonLabel: 'Estacionalidad en Salud',
    seasonSubtitle: 'Cuándo los pacientes buscan atención',
    seasonDesc: 'La demanda de servicios de salud tiene picos claros. Invertir en el momento correcto reduce tu CPL.',
    seasonality: [
      { m:'Ene', level:3, tip:'Chequeos de año nuevo y propósitos de salud. Alta demanda de medicina preventiva.', budget:'Escala' },
      { m:'Feb', level:2, tip:'Demanda estable. Estética y bienestar post-diciembre. Buena época para captación.', budget:'Normal' },
      { m:'Mar', level:2, tip:'Temporada de alergias y cambios de clima. Campañas de medicina general funcionan bien.', budget:'Normal' },
      { m:'Abr', level:2, tip:'Revisiones pre-verano. Dentistas y estética tienen demanda alta de procedimientos.', budget:'Normal' },
      { m:'May', level:3, tip:'Día de las Madres activa tratamientos estéticos. Escala si tienes servicios de belleza médica.', budget:'Escala' },
      { m:'Jun', level:2, tip:'Pre-verano. Demanda de estética, dermatología y nutrición se mantiene alta.', budget:'Normal' },
      { m:'Jul', level:1, tip:'Vacaciones: muchos posponen citas. CPL sube. Mantén presencia mínima.', budget:'Reduce' },
      { m:'Ago', level:2, tip:'Regreso a clases activa demanda de pediatría y optometría. Buena temporada.', budget:'Normal' },
      { m:'Sep', level:2, tip:'Temporada de gripes y alergias. Medicina general y preventiva con alta demanda.', budget:'Normal' },
      { m:'Oct', level:2, tip:'Campañas de vacunación y salud preventiva. Estabilidad en la mayoría de especialidades.', budget:'Normal' },
      { m:'Nov', level:1, tip:'Buen Fin no aplica. Demanda baja mientras gente prepara festividades.', budget:'Reduce' },
      { m:'Dic', level:1, tip:'Mes difícil. Pacientes posponen. Guarda presupuesto para enero de propósitos.', budget:'Pausa' },
    ],
  },

  retail: {
    label: 'Herramientas de Retail',
    calc: {
      title: 'Proyección de Ventas',
      icon: '🛍️',
      desc: 'Estima los ingresos que generará tu tráfico de anuncios con base en ticket, conversión y frecuencia.',
      f1Label: 'Visitantes / leads de ads', f1P: 'ej. 200',
      f2Label: 'Ticket promedio (MXN)', f2P: 'ej. 650',
      f3Label: 'Tasa de conversión (%)', f3P: '3', f3D: '3',
      f4Label: 'Compras/mes por cliente', f4P: '1.5', f4D: '1.5',
      hasGoal: true, goalLabel: 'Meta mensual de ventas (MXN, opcional)', goalP: 'ej. 80,000',
      resultTitle: 'Ventas proyectadas',
      resultUnit: 'en ingresos estimados',
      compute: (l,p,c,r) => l*(c/100)*p*r,
      sub: (l,p,c,r) => `${Math.round(l*(c/100))} compradores · ${r}x compras/mes`,
    },
    diagDesc: 'Evalúa tu ecosistema digital para atraer compradores a tu tienda física o e-commerce.',
    seasonLabel: 'Estacionalidad Retail',
    seasonSubtitle: 'Cuándo escalar tu inversión en ads de tienda',
    seasonDesc: 'El retail tiene picos muy marcados. Saber cuándo invertir puede triplicar tu ROI.',
    seasonality: [
      { m:'Ene', level:2, tip:'Liquidaciones post-navidad y ropa de temporada. Mantén presencia con ofertas de inventario.', budget:'Normal' },
      { m:'Feb', level:3, tip:'San Valentín dispara ventas de regalos, accesorios y moda. Escala desde el día 1.', budget:'Escala' },
      { m:'Mar', level:2, tip:'Temporada tranquila. Ideal para lanzar nuevas colecciones de primavera-verano.', budget:'Normal' },
      { m:'Abr', level:2, tip:'Semana Santa activa compras de ropa de playa y accesorios de temporada.', budget:'Normal' },
      { m:'May', level:3, tip:'Día de las Madres: uno de los mayores picos de ventas del año en retail. Escala fuerte.', budget:'Escala' },
      { m:'Jun', level:2, tip:'Temporada de verano y ropa de playa. Mantén presencia en categorías estacionales.', budget:'Normal' },
      { m:'Jul', level:2, tip:'Vacaciones. Tráfico variable. Activa remarketing para visitantes de temporada.', budget:'Normal' },
      { m:'Ago', level:2, tip:'Regreso a clases: uniforme, útiles, mochila. Muy buen momento si tienes estas categorías.', budget:'Normal' },
      { m:'Sep', level:2, tip:'Temporada de otoño. Lanzamientos de nuevas colecciones.', budget:'Normal' },
      { m:'Oct', level:2, tip:'Pre-Buen Fin. Activa listas de deseos y campañas de expectativa.', budget:'Normal' },
      { m:'Nov', level:3, tip:'Buen Fin y Black Friday: el mes de mayor venta del año. Presupuesto máximo sin dudar.', budget:'Escala' },
      { m:'Dic', level:3, tip:'Navidad y Reyes. Ventas de regalo altas. Escala todo diciembre.', budget:'Escala' },
    ],
  },

  education: {
    label: 'Herramientas de Educación',
    calc: {
      title: 'Proyección de Matrículas',
      icon: '🎓',
      desc: 'Calcula los ingresos esperados de tus leads según el precio del curso y tu tasa de conversión.',
      f1Label: 'Leads / solicitudes', f1P: 'ej. 70',
      f2Label: 'Precio del curso (MXN)', f2P: 'ej. 3,500',
      f3Label: 'Tasa de conversión (%)', f3P: '20', f3D: '20',
      f4Label: 'Cursos adicionales / upsell', f4P: '1.2', f4D: '1.2',
      hasGoal: true, goalLabel: 'Meta mensual de ingresos (MXN, opcional)', goalP: 'ej. 80,000',
      resultTitle: 'Ingresos por matrículas',
      resultUnit: 'en ingresos proyectados',
      compute: (l,p,c,r) => l*(c/100)*p*r,
      sub: (l,p,c,r) => `${Math.round(l*(c/100))} alumnos nuevos · ${r}x cursos promedio`,
    },
    diagDesc: 'Evalúa tu infraestructura digital para atraer alumnos y crecer tu academia o servicio de coaching.',
    seasonLabel: 'Estacionalidad Educativa',
    seasonSubtitle: 'Cuándo hay más demanda de aprendizaje',
    seasonDesc: 'Los ciclos escolares y las temporadas de propósitos marcan la demanda educativa. Anticípate.',
    seasonality: [
      { m:'Ene', level:3, tip:'Propósitos de año nuevo: aprender algo nuevo está en el top. Máxima demanda de cursos.', budget:'Escala' },
      { m:'Feb', level:2, tip:'Demanda estable. Buen momento para campañas de becas o pagos diferidos.', budget:'Normal' },
      { m:'Mar', level:3, tip:'Pre-verano: muchos buscan capacitarse antes de temporada alta de empleo.', budget:'Escala' },
      { m:'Abr', level:2, tip:'Semana Santa pausa un poco. Activa retargeting a quienes mostraron interés.', budget:'Normal' },
      { m:'May', level:3, tip:'Fin de ciclo escolar activa búsqueda de cursos de verano y certificaciones.', budget:'Escala' },
      { m:'Jun', level:3, tip:'Cursos de verano y capacitación profesional. Alta demanda. Escala.', budget:'Escala' },
      { m:'Jul', level:2, tip:'Verano. Cursos en línea mantienen demanda. Enfócate en contenido digital.', budget:'Normal' },
      { m:'Ago', level:2, tip:'Regreso a clases reactiva educación complementaria y tutorías.', budget:'Normal' },
      { m:'Sep', level:2, tip:'Inicio de ciclo. Demanda de cursos de actualización y certificaciones.', budget:'Normal' },
      { m:'Oct', level:2, tip:'Mitad de ciclo. Activa campañas de inscripción anticipada para el siguiente.', budget:'Normal' },
      { m:'Nov', level:1, tip:'Buen Fin puede funcionar con cursos en oferta. Fuera de eso, demanda baja.', budget:'Reduce' },
      { m:'Dic', level:1, tip:'Diciembre: temporada de fiestas frena inscripciones. Prepara enero.', budget:'Pausa' },
    ],
  },

  services: {
    label: 'Herramientas de Servicios',
    calc: {
      title: 'Proyección de Contratos',
      icon: '⚖️',
      desc: 'Estima el valor de tus leads según tu tasa de cierre, valor de contrato y duración promedio.',
      f1Label: 'Leads / prospectos', f1P: 'ej. 30',
      f2Label: 'Valor mensual de contrato (MXN)', f2P: 'ej. 5,000',
      f3Label: 'Tasa de cierre (%)', f3P: '15', f3D: '15',
      f4Label: 'Meses de contrato promedio', f4P: '6', f4D: '6',
      hasGoal: true, goalLabel: 'Meta mensual de ingresos (MXN, opcional)', goalP: 'ej. 100,000',
      resultTitle: 'Valor de contratos',
      resultUnit: 'en ingresos proyectados',
      compute: (l,p,c,r) => l*(c/100)*p*r,
      sub: (l,p,c,r) => `${Math.round(l*(c/100))} contratos · ${r} meses promedio`,
    },
    diagDesc: 'Evalúa tu presencia digital para atraer clientes a tu despacho, consultoría o servicio profesional.',
    seasonLabel: 'Estacionalidad de Servicios',
    seasonSubtitle: 'Cuándo contratan más los clientes',
    seasonDesc: 'Los servicios B2B y profesionales tienen ciclos ligados al calendario fiscal y empresarial.',
    seasonality: [
      { m:'Ene', level:3, tip:'Inicio de año fiscal. Empresas contratan servicios nuevos con presupuesto fresco. Escala.', budget:'Escala' },
      { m:'Feb', level:3, tip:'Alta demanda de contadores y despachos fiscales por declaraciones de enero.', budget:'Escala' },
      { m:'Mar', level:3, tip:'Cierre fiscal para muchas empresas. Contadores, abogados y consultores muy solicitados.', budget:'Escala' },
      { m:'Abr', level:2, tip:'Post-cierre fiscal. Demanda baja un poco. Reactiva con propuestas de mejora de procesos.', budget:'Normal' },
      { m:'May', level:2, tip:'Planificación de presupuesto Q3. Buen momento para agendar propuestas.', budget:'Normal' },
      { m:'Jun', level:2, tip:'Mitad de año. Revisión de contratos y renovaciones. Activa campañas de fidelización.', budget:'Normal' },
      { m:'Jul', level:1, tip:'Vacaciones ejecutivas. Decisiones de contratación se posponen. Reduce ads.', budget:'Reduce' },
      { m:'Ago', level:2, tip:'Regreso a operaciones. Empresas reactivan proyectos pospuestos en verano.', budget:'Normal' },
      { m:'Sep', level:3, tip:'Q4 planning: empresas contratan servicios para cerrar el año fuerte. Escala.', budget:'Escala' },
      { m:'Oct', level:3, tip:'Alta demanda de consultoría, legal y fiscal para cierres anuales. Muy buen período.', budget:'Escala' },
      { m:'Nov', level:2, tip:'Últimas contrataciones del año. Aprovecha el presupuesto que "sobra" en las empresas.', budget:'Normal' },
      { m:'Dic', level:1, tip:'Cierre de año. Pocas decisiones nuevas. Prepara propuestas para enero.', budget:'Reduce' },
    ],
  },

  construction: {
    label: 'Herramientas de Construcción',
    calc: {
      title: 'Pipeline de Proyectos',
      icon: '🏗️',
      desc: 'Calcula el margen potencial de tus leads considerando valor de proyecto, cierre y margen de obra.',
      f1Label: 'Leads / solicitudes de cotización', f1P: 'ej. 20',
      f2Label: 'Valor promedio de proyecto (MXN)', f2P: 'ej. 500,000',
      f3Label: 'Tasa de cierre (%)', f3P: '10', f3D: '10',
      f4Label: 'Margen de utilidad (%)', f4P: '25', f4D: '25',
      hasGoal: true, goalLabel: 'Meta mensual de utilidad (MXN, opcional)', goalP: 'ej. 80,000',
      resultTitle: 'Margen potencial',
      resultUnit: 'en utilidad proyectada',
      compute: (l,p,c,r) => l*(c/100)*p*(r/100),
      sub: (l,p,c,r) => `${Math.round(l*(c/100))} proyectos · ${r}% margen promedio`,
    },
    diagDesc: 'Evalúa tu presencia digital para atraer proyectos de construcción, remodelación y arquitectura.',
    seasonLabel: 'Estacionalidad en Construcción',
    seasonSubtitle: 'Cuándo los clientes contratan obra',
    seasonDesc: 'Los proyectos de construcción se planifican con meses de anticipación. Anticipa la demanda.',
    seasonality: [
      { m:'Ene', level:2, tip:'Año nuevo, proyectos nuevos. Muchos clientes activan presupuesto aprobado en diciembre.', budget:'Normal' },
      { m:'Feb', level:2, tip:'Inicio de proyectos residenciales. Temporada de solicitudes de cotización.', budget:'Normal' },
      { m:'Mar', level:3, tip:'Temporada alta de inicio de obra antes del calor. Muy alta demanda de cotizaciones.', budget:'Escala' },
      { m:'Abr', level:3, tip:'El mes ideal para iniciar obra en la mayoría del país. Escala campañas de cotización.', budget:'Escala' },
      { m:'May', level:3, tip:'Alta demanda, especialmente en remodelaciones residenciales pre-verano.', budget:'Escala' },
      { m:'Jun', level:2, tip:'Inicio de lluvias en muchas zonas. Mantén presencia pero la demanda baja.', budget:'Normal' },
      { m:'Jul', level:1, tip:'Temporada de lluvias. Proyectos en pausa. Reduce y usa el período para contenido de portafolio.', budget:'Reduce' },
      { m:'Ago', level:1, tip:'Continúan lluvias. Temporada baja. Activa campañas de planeación para septiembre.', budget:'Reduce' },
      { m:'Sep', level:2, tip:'Fin de lluvias. Reactiva campañas. Clientes planifican proyectos de Q4.', budget:'Normal' },
      { m:'Oct', level:3, tip:'Temporada alta de otoño. Muchos quieren terminar proyectos antes del frío navideño.', budget:'Escala' },
      { m:'Nov', level:2, tip:'Buena demanda. Proyectos de año nuevo empiezan a planificarse.', budget:'Normal' },
      { m:'Dic', level:1, tip:'Navidad pausa proyectos. Usa el tiempo para preparar campañas de enero.', budget:'Reduce' },
    ],
  },
}
